EmbedSample/Models/ReportViewModel.cs
using Microsoft.PowerBI.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.PowerBI.Api.V1.Models;

namespace paas_demo.Models
{
    public class ReportViewModel
    {
        public Report Report { get; set; }

        public string AccessToken { get; set; }
    }
}

EmbedSample/Models/ReportsViewModel.cs
using System.Collections.Generic;
using Microsoft.PowerBI.Api.V1.Models;

namespace paas_demo.Models
{
    public class ReportsViewModel
    {
        public List<Report> Reports { get; set; }
    }
}

EmbedSample/Controllers/DashboardController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.PowerBI.Api.V1;
using Microsoft.PowerBI.Security;
using Microsoft.Rest;
using paas_demo.Models;

namespace paas_demo.Controllers
{
    public class DashboardController : Controller
    {
        private readonly string workspaceCollection;
        private readonly string workspaceId;
        private readonly string accessKey;
        private readonly string apiUrl;

        public DashboardController()
        {
            this.workspaceCollection = ConfigurationManager.AppSettings["powerbi:WorkspaceCollection"];
            this.workspaceId = ConfigurationManager.AppSettings["powerbi:WorkspaceId"];
            this.accessKey = ConfigurationManager.AppSettings["powerbi:AccessKey"];
            this.apiUrl = ConfigurationManager.AppSettings["powerbi:ApiUrl"];
        }

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult Reports()
        {
            using (var client = this.CreatePowerBIClient())
            {
                var reportsResponse = client.Reports.GetReports(this.workspaceCollection, this.workspaceId);

                var viewModel = new ReportsViewModel
                {
                    Reports = reportsResponse.Value.ToList()
                };

                return PartialView(viewModel);
            }
        }

        public async Task<ActionResult> Report(string reportId)
        {
            using (var client = this.CreatePowerBIClient())
            {
                var reportsResponse = await client.Reports.GetReportsAsync(this.workspaceCollection, this.workspaceId);
                var report = reportsResponse.Value.FirstOrDefault(r => r.Id == reportId);
                var embedToken = PowerBIToken.CreateReportEmbedToken(this.workspaceCollection, this.workspaceId, report.Id);

                var viewModel = new ReportViewModel
                {
                    Report = report,
                    AccessToken = embedToken.Generate(this.accessKey)
                };

                return View(viewModel);
            }
        }

        private IPowerBIClient CreatePowerBIClient()
        {
            var credentials = new TokenCredentials(accessKey, "AppKey");
            var client = new PowerBIClient(credentials)
            {
                BaseUri = new Uri(apiUrl)
            };

            return client;
        }
    }
}

EmbedSample/Views/Dashboard/Index.cshtml
@section Breadcrumbs{
    <ol class="breadcrumb navbar-breadcrumb">
        <li>Dashboard</li>
    </ol>
}

<div class="side-body padding-top">
    @Html.PowerBIAccessToken()
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <a href="#">
                <div class="card red summary-inline">
                    <div class="card-body">
                        <i class="icon fa fa-inbox fa-4x"></i>
                        <div class="content">
                            <div class="title">50</div>
                            <div class="sub-title">New Mails</div>
                        </div>
                        <div class="clear-both"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <a href="#">
                <div class="card yellow summary-inline">
                    <div class="card-body">
                        <i class="icon fa fa-comments fa-4x"></i>
                        <div class="content">
                            <div class="title">23</div>
                            <div class="sub-title">New Message</div>
                        </div>
                        <div class="clear-both"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <a href="#">
                <div class="card green summary-inline">
                    <div class="card-body">
                        <i class="icon fa fa-tags fa-4x"></i>
                        <div class="content">
                            <div class="title">280</div>
                            <div class="sub-title">Product View</div>
                        </div>
                        <div class="clear-both"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <a href="#">
                <div class="card blue summary-inline">
                    <div class="card-body">
                        <i class="icon fa fa-share-alt fa-4x"></i>
                        <div class="content">
                            <div class="title">16</div>
                            <div class="sub-title">Share</div>
                        </div>
                        <div class="clear-both"></div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="row  no-margin-bottom">
        <div class="col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-xs-12">
                    <div class="card primary">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="thumbnail no-margin-bottom">
                        <img src="../img/thumbnails/picjumbo.com_IMG_4566.jpg" class="img-responsive">
                        <div class="caption">
                            <h3 id="thumbnail-label">Thumbnail label<a class="anchorjs-link" href="#thumbnail-label"><span class="anchorjs-icon"></span></a></h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="thumbnail no-margin-bottom">
                        <img src="../img/thumbnails/picjumbo.com_IMG_3241.jpg" class="img-responsive">
                        <div class="caption">
                            <h3 id="thumbnail-label">Thumbnail label<a class="anchorjs-link" href="#thumbnail-label"><span class="anchorjs-icon"></span></a></h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="card primary">
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="card primary">
                    </div>
                </div>
            </div>
            <div class="card card-success">
                <div class="card-header">
                    <div class="card-title">
                        <div class="title"><i class="fa fa-comments-o"></i> Last Message</div>
                    </div>
                    <div class="clear-both"></div>
                </div>
                <div class="card-body no-padding">
                    <ul class="message-list">
                        <a href="#">
                            <li>
                                <img src="../img/profile/profile-1.jpg" class="profile-img pull-left">
                                <div class="message-block">
                                    <div>
                                        <span class="username">Tui2Tone</span> <span class="message-datetime">12 min ago</span>
                                    </div>
                                    <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
                                </div>
                            </li>
                        </a>
                        <a href="#">
                            <li>
                                <img src="../img/profile/profile-1.jpg" class="profile-img pull-left">
                                <div class="message-block">
                                    <div>
                                        <span class="username">Tui2Tone</span> <span class="message-datetime">15 min ago</span>
                                    </div>
                                    <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
                                </div>
                            </li>
                        </a>
                        <a href="#">
                            <li>
                                <img src="../img/profile/profile-1.jpg" class="profile-img pull-left">
                                <div class="message-block">
                                    <div>
                                        <span class="username">Tui2Tone</span> <span class="message-datetime">2 hour ago</span>
                                    </div>
                                    <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
                                </div>
                            </li>
                        </a>
                        <a href="#">
                            <li>
                                <img src="../img/profile/profile-1.jpg" class="profile-img pull-left">
                                <div class="message-block">
                                    <div>
                                        <span class="username">Tui2Tone</span> <span class="message-datetime">1 day ago</span>
                                    </div>
                                    <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
                                </div>
                            </li>
                        </a>
                        <a href="#" id="message-load-more">
                            <li class="text-center load-more">
                                <i class="fa fa-refresh"></i> load more..
                            </li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

EmbedSample/Views/Dashboard/Report.cshtml
@model ReportViewModel

@section Breadcrumbs {
    <ol class="breadcrumb navbar-breadcrumb">
        <li>Reports</li>
        <li>@Model.Report.Name</li>
        <li class="active" id="page-name"></li>
    </ol>
}
<div class="side-body padding-top">
    <div class="col-md-9">
        @Html.PowerBIReportFor(m => m.Report, new { id = "pbi-report", style = "height:85vh", powerbi_access_token = Model.AccessToken })
    </div>
    <div class="col-md-3">
        <h3>Page Navigation</h3>
        <div>
            <button id="pbi-prev-page" class="btn btn-default">Previous Page</button>
            <button id="pbi-next-page" class="btn btn-default">Next Page</button>
        </div>
        <h3>Settings</h3>
        <div>
            <div class="checkbox">
                <label>
                    <input id="setting-shownav" type="checkbox" checked="checked" /> Show Navigation
                </label>
            </div>
            <div class="checkbox">
                <label>
                    <input id="setting-showfilterpane" type="checkbox" /> Show Filter Pane
                </label>
            </div>
        </div>
        <h3>Filters</h3>
        <button id="filter-clear" type="button" class="btn btn-danger">Clear All Filters</button>
        <h4>Add Filter</h4>
        <form id="filter-form">
            <div class="form-group">
                <label for="filter-target">Target</label>
                <select id="filter-target" class="form-control">
                    <option value="report">Report</option>
                    <option value="page">Page</option>
                </select>
            </div>
            <div class="form-group">
                <label for="filter-table">Table</label>
                <input type="text" class="form-control" id="filter-table" />
            </div>
            <div class="form-group">
                <label for="filter-column">Column / Measure</label>
                <input type="text" class="form-control" id="filter-column" />
            </div>
            <div class="form-group">
                <label for="filter-value">Value</label>
                <input type="text" class="form-control" id="filter-value" />
            </div>
            <button id="filter-add" type="button" class="btn btn-success">Add Filter</button>
        </form>
    </div>

    @{ 
        var liveSampleUrl = "https://microsoft.github.io/PowerBI-JavaScript/demo/code-demo/index.html?";
        liveSampleUrl += "?embedUrl=" + Url.Encode(Model.Report.EmbedUrl);
        liveSampleUrl += "?embedId=" + Url.Encode(Model.Report.Id);
        liveSampleUrl += "&accessToken=" + Url.Encode(Model.AccessToken);
    }

    <div class="col-md-3 livesamplelink">
        Embed and play with current report using <a href="@liveSampleUrl">Embedded Live Sample</a>
    </div>
</div>

@section PageScripts {
    <script>
        $(function () {
            // For complete list of embed configuration see the following wiki page
            // https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details
            var reportConfig = {
                settings: {
                    filterPaneEnabled: false
                }
            };
            var reportElement = document.getElementById('pbi-report');
            var pageName = document.getElementById('page-name');

            // Embed report
            // https://microsoft.github.io/PowerBI-JavaScript/classes/_src_service_.service.html#embed
            var report = powerbi.embed(reportElement, reportConfig);

            var pages = [];
            var pageIndex = 0;
            var currentPage = null;

            // For a complete guide to event handling see the following wiki page
            // https://github.com/Microsoft/PowerBI-JavaScript/wiki/Handling-Events
            report.on('loaded',
                function () {
                    // Get report pages
                    // https://microsoft.github.io/PowerBI-JavaScript/classes/_src_report_.report.html#getpages
                    report.getPages()
                        .then(function (reportPages) {
                            pages = reportPages;
                        });
                });

            // Handling pageChanged event
            // https://microsoft.github.io/PowerBI-JavaScript/classes/_src_report_.report.html#on
            report.on('pageChanged',
                function (e) {
                    currentPage = e.detail.newPage;
                    pageName.innerText = e.detail.newPage.displayName;

                    if (pages.length === 0) {
                        return;
                    }

                    pageIndex = pages.findIndex(function (el) {
                        return el.name === e.detail.newPage.name;
                    });
                });

            // For a complete guide to page navigation see the following wiki page
            // https://github.com/Microsoft/PowerBI-JavaScript/wiki/Page-Navigation
            function changePage(direction) {
                var nextPageIndex = pageIndex + direction;
                if (nextPageIndex < 0) nextPageIndex = pages.length - 1;
                if (nextPageIndex >= pages.length) nextPageIndex = 0;

                pages[nextPageIndex].setActive();
            }

            // For a complete guide to setting filters see the following wiki page
            // https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters
            function addFilter() {
                var target = $('#filter-target').val();
                var table = $('#filter-table').val();
                var column = $('#filter-column').val();
                var value = $('#filter-value').val();

                var basicFilter = {
                    $schema: "http://powerbi.com/product/schema#basic",
                    target: {
                        table: table,
                        column: column
                    },
                    operator: 'In',
                    values: [value]
                };

                var filterTarget = target === 'page' ? currentPage : report;
                // Get existing filters and append a new filter
                // https://microsoft.github.io/PowerBI-JavaScript/interfaces/_src_ifilterable_.ifilterable.html#getfilters
                filterTarget.getFilters().then(function (allTargetFilters) {
                    allTargetFilters.push(basicFilter);

                    // Set filters
                    // https://microsoft.github.io/PowerBI-JavaScript/interfaces/_src_ifilterable_.ifilterable.html#setfilters
                    filterTarget.setFilters(allTargetFilters);
                });


                $('#filter-form')[0].reset();
            }

            function clearFilters() {
                // Remove report filters
                // https://microsoft.github.io/PowerBI-JavaScript/classes/_src_report_.report.html#removefilters
                report.removeFilters();
                pages.forEach(function (page) {
                    // Remove page filters
                    // https://microsoft.github.io/PowerBI-JavaScript/classes/_src_page_.page.html#removefilters
                    page.removeFilters();
                });
            }

            // For a full list of configurable settings see the following wiki page
            // https://github.com/Microsoft/PowerBI-JavaScript/wiki/Settings
            function updateSetting(e, settingName) {
                var settings = {};
                settings[settingName] = e.target.checked;
                report.updateSettings(settings);
            }

            $('#pbi-prev-page').on('click', function () { changePage(-1); });
            $('#pbi-next-page').on('click', function () { changePage(1); });

            $('#setting-shownav').on('change', function (e) { updateSetting(e, 'navContentPaneEnabled'); });
            $('#setting-showfilterpane').on('change', function (e) { updateSetting(e, 'filterPaneEnabled'); });

            $('#filter-add').on('click', function () { addFilter(); });
            $('#filter-clear').on('click', function () { clearFilters(); });
        });
    </script>
}

EmbedSample/Views/Shared/Reports.cshtml
@model ReportsViewModel
@{
    Layout = null;

    var classNames = "panel panel-default dropdown";

    if (this.Request.Path.IndexOf("Report") > -1)
    {
        classNames += " active";
    }
}

<li class="@classNames">
    <a data-toggle="collapse" href="#reports-nav">
        <span class="icon fa fa-bar-chart"></span><span class="title">Reports</span>
    </a>
    <!-- Dropdown level 1 -->
    <div id="reports-nav" class="panel-collapse collapse">
        <div class="panel-body">
            <ul class="nav navbar-nav">
                @foreach (var report in Model.Reports)
                {
                    var reportClass = Request.QueryString["reportId"] == report.Id ? "active" : "";
                    <li class="@reportClass">
                        @Html.ActionLink(report.Name, "Report", new { reportId = report.Id })
                    </li>
                }
            </ul>
        </div>
    </div>
</li>

EmbedSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Contoso</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="/lib/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/animate.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/bootstrap-switch.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/checkbox3.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/dataTables.bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/select2.min.css">
    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/themes/flat-blue.css">
    <link href="~/Content/powerbi.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body class="flat-blue">
    <div class="app-container">
        <div class="row content-container">
            <nav class="navbar navbar-default navbar-fixed-top navbar-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-expand-toggle">
                            <i class="fa fa-bars icon"></i>
                        </button>
                        @RenderSection("Breadcrumbs", false)
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-th icon"></i>
                        </button>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-times icon"></i>
                        </button>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-comments-o"></i></a>
                            <ul class="dropdown-menu animated fadeInDown">
                                <li class="title">
                                    Notification <span class="badge pull-right">0</span>
                                </li>
                                <li class="message">
                                    No new notification
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown danger">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-star-half-o"></i> 4</a>
                            <ul class="dropdown-menu danger  animated fadeInDown">
                                <li class="title">
                                    Notification <span class="badge pull-right">4</span>
                                </li>
                                <li>
                                    <ul class="list-group notifications">
                                        <a href="#">
                                            <li class="list-group-item">
                                                <span class="badge">1</span> <i class="fa fa-exclamation-circle icon"></i> new registration
                                            </li>
                                        </a>
                                        <a href="#">
                                            <li class="list-group-item">
                                                <span class="badge success">1</span> <i class="fa fa-check icon"></i> new orders
                                            </li>
                                        </a>
                                        <a href="#">
                                            <li class="list-group-item">
                                                <span class="badge danger">2</span> <i class="fa fa-comments icon"></i> customers messages
                                            </li>
                                        </a>
                                        <a href="#">
                                            <li class="list-group-item message">
                                                view all
                                            </li>
                                        </a>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown profile">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Emily Hart <span class="caret"></span></a>
                            <ul class="dropdown-menu animated fadeInDown">
                                <li class="profile-img">
                                    <img src="../img/profile/picjumbo.com_HNCK4153_resize.jpg" class="profile-img">
                                </li>
                                <li>
                                    <div class="profile-info">
                                        <h4 class="username">Emily Hart</h4>
                                        <p>emily_hart@email.com</p>
                                        <div class="btn-group margin-bottom-2x" role="group">
                                            <button type="button" class="btn btn-default"><i class="fa fa-user"></i> Profile</button>
                                            <button type="button" class="btn btn-default"><i class="fa fa-sign-out"></i> Logout</button>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="side-menu sidebar-inverse">
                <nav class="navbar navbar-default" role="navigation">
                    <div class="side-menu-container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <div class="icon fa fa-paper-plane"></div>
                                <div class="title">Contoso</div>
                            </a>
                            <button type="button" class="navbar-expand-toggle pull-right visible-xs">
                                <i class="fa fa-times icon"></i>
                            </button>
                        </div>
                        <ul class="nav navbar-nav">
                            @{
                                var className = Request.Path == "/" && Request.QueryString.Count == 0 ? "active" : "";
                            }
                            <li class="@className">
                                <a href="/">
                                    <span class="icon fa fa-home"></span><span class="title">Home</span>
                                </a>
                            </li>
                            @Html.Action("Reports", "Dashboard")
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
            </div>
            <!-- Main Content -->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <footer class="app-footer">
            <div class="wrapper">
                <span class="pull-right">2.1 <a href="#"><i class="fa fa-long-arrow-up"></i></a></span> © 2015 Copyright.
            </div>
        </footer>
    </div>
    <!-- Javascript Libs -->
    <script type="text/javascript" src="/lib/js/jquery.min.js"></script>
    <script type="text/javascript" src="/lib/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/lib/js/Chart.min.js"></script>
    <script type="text/javascript" src="/lib/js/bootstrap-switch.min.js"></script>
    <script type="text/javascript" src="/lib/js/jquery.matchHeight-min.js"></script>
    <script type="text/javascript" src="/lib/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/lib/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="/lib/js/select2.full.min.js"></script>
    <script type="text/javascript" src="/lib/js/es6-promise.auto.min.js"></script>
    <script type="text/javascript" src="/lib/js/ace/ace.js"></script>
    <script type="text/javascript" src="/lib/js/ace/mode-html.js"></script>
    <script type="text/javascript" src="/lib/js/ace/theme-github.js"></script>
    <!-- Javascript -->
    <script type="text/javascript" src="/js/app.js"></script>
    <script src="~/Scripts/powerbi.js"></script>
    @RenderSection("PageScripts", false)
</body>
</html>